### ISSUE TITLE
issue : python 3.12에서는 distuils를 지원하지 않음

### ISSUE THREAD

**Issue by youngkwangjoo** [glory-coffee-project/back-end-coffee#31]
새로 서버를 구축하며 컨테이너를 빌드하는 과정에서

distuils를 지원하지 않아서 빌드와 다운이 되지않는 문제 발생 

joo@liv:~/back-end-coffee$ docker-compose -f docker-compose-pro.yml build
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/docker-compose", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 9, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils'

확인해보니 distutils는 파있너 빌드와 배포를 도와주는 라이브러리인데 3.12부터는 지원하지 않고 다른걸로 바뀜

파이썬 버전을 낮출까 고민하다가

docker compose v2는 파이썬 의존성없이 배포가 가능하고 독립적으로 시행한다는걸 확인함

나중에 문제가 되지 않을까 했지만, 우선 빌드와 배포 과정에서 distutils가 사용된다면 그 이후단계에서는 없어도 무방할거라 판단되서

v2로 docker를 실행하기로함

**Comment by youngkwangjoo** [comment]
docker v2로 진행함
